name: Test To-Do Service test tools

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'tools/**'
  workflow_dispatch:

jobs:
  test-tools:
    name: Run Tool Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install pyyaml pytest --break-system-packages
      
      - name: Run all tool tests
        run: |
          cd tools/tests
          pytest -v
